Fix hostfile issue when using slots with MPICH
MPICH doesn't recognize the OpenMPI format for specifying the number
of slots. If configured for vanilla MPI (MPICH) and a number of slots
is specified, there will be an error parsing the hostfile, causing
IO500 to fail. Fix that by checking the MPI type and crafting the
hostfile entries accordingly.

diff --git a/script b/script
--- a/script
+++ b/script
@@ -981,7 +981,17 @@ then
 		*******************************************************
 
 		SLOTS_MSG
+	elif [ "$OB_MPI_TYPE" = "vanilla" ]
+	then
+		# MPICH wants the format "<HOST>:<NUM_SLOTS>"
+		sed -i "s/$/:$OB_SLOTS/" hostfile
+		if [ "$?" -gt "0" ]
+		then
+			echo "adding slots to hostfile failed."
+			ob_cleanup
+		fi
 	else
+		# OpenMPI wants the format "<HOST> slots=<NUM_SLOTS>"
 		sed -i "s/$/ slots=$OB_SLOTS/" hostfile
 		if [ "$?" -gt "0" ]
 		then
