script: add support for various mpi types
Signed-off-by: Mike Marshall <hubcap@omnibond.com>

diff --git a/script b/script
--- a/script
+++ b/script
@@ -1,6 +1,5 @@
 #!/bin/bash
 # TODO:
-#  mount the results bucket as a filesystem on OB_IO500_NAMEa
 #  delete all instances at cleanup and depend upon the results bucket?
 
 # function to call on normal exit and on any failure
@@ -18,9 +17,15 @@ gcloud config set compute/region "$OB_REGION"
 gcloud config set compute/zone "$OB_ZONE"
 gcloud config set project "$OB_PROJECT"
 
+#OB_MPI_TYPE="intel"
+#OB_MPI_TYPE="openmpi"
+OB_MPI_TYPE="vanilla"
+
 #OB_IMAGE=" --image hubcap-fc34-guestenv-gvnic-io500"
 #OB_IMAGE=" --image hubcap-fc34-guestenv-gvnic-io500-2"
-OB_IMAGE=" --image hubcap-fc34-guestenv-gvnic-io500-3"
+#OB_IMAGE=" --image hubcap-fc34-guestenv-gvnic-io500-3"
+OB_IMAGE=" --image hubcap-io500-oiv1"
+
 OB_SCOPE=" --scopes=cloud-platform"
 
 # persistant place for results and configs and whatever.
@@ -35,7 +40,8 @@ OB_OFS_MACHINE=" --machine-type=n1-standard-1"
 #OB_OFS_MACHINE=" --machine-type=n2-standard-80"
 
 OB_IO500_CLIENTS=2
-OB_IO500_MACHINE=" --machine-type=n1-standard-1"
+#OB_IO500_MACHINE=" --machine-type=n1-standard-1"
+OB_IO500_MACHINE=" --machine-type=n1-standard-16"
 
 # MAX per instance: 24 local SSD partitions - 9 TB - 2.4 million read IOPS
 # My observation is that nvme device names will be /dev/nvme0n1 - /dev/nvme0n24
@@ -516,13 +522,75 @@ do
 done
 echo " done."
 
-# copy config files over to the "a" io500 client and run io500
-if [ "$OB_IO500_CLIENTS" -gt "0" ]
+# We used hostfile to extend /etc/hosts on all the instances
+# with the names of all the orangefs servers and all the io500
+# clients. Now we'll remove all the orangefs servers from hostfile
+# and all of the client's IP addrs and use hostfile as a list
+# of client names to run io500 on.
+sed -i "/${OB_OFS_NAME}/d" hostfile
+if [ "$?" -gt "0" ]
 then
-	OB_EX_IP="${OB_EX_ETC_HOSTS["$OB_IO500_NAME""a"]}"
-	OB_HOST="$OB_IO500_NAME""a"
+	echo "purge of servers in hostfile failed."
+	ob_cleanup
+fi
+sed -i "s/^.* //" hostfile
+if [ "$?" -gt "0" ]
+then
+	echo "purge of ip addrs in hostfile failed."
+	ob_cleanup
+fi
+
+if [ "$OB_MPI_TYPE" = "openmpi" ]
+then
+	OB_MPI_REPO="/home/io500_openmpi"
+elif [ "$OB_MPI_TYPE" = "intel" ]
+then
+	OB_MPI_REPO="/home/io500_intel"
+else
+	OB_MPI_REPO="/home/io500_vanilla"
+fi
+
+# If mpi type is set to openmpi, then we need to provide
+# proper paths to the io500 clients in order to avoid the dreaded
+# "orted: command not found"...
+if [ "$OB_MPI_TYPE" = "openmpi" ]
+then
+	echo -n "add openmpi vars to .bashrc on io500 clients."
+	for i in `seq 1 $OB_IO500_CLIENTS`
+	do
+		OB_EX_IP="${OB_EX_ETC_HOSTS["$OB_IO500_NAME""${OB_ALPHA[i]}"]}"
+		OB_HOST="$OB_IO500_NAME""${OB_ALPHA[i]}"
+		ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
+			sudo gsutil cp "$OB_BUCKET"/openmpivars . \
+				> /dev/null 2>&1
+		if [ "$?" -gt "0" ]
+		then
+			echo "bucket cp openmpi path to :""$OB_HOST"": failed."
+			ob_cleanup
+		fi
+
+		ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
+			sudo sh -c \'cat openmpivars \>\> .bashrc\' \
+				> /dev/null 2>&1
+		if [ "$?" -gt "0" ]
+		then
+			echo -e "\nappend opempivars on :"$OB_HOST": failed."
+			ob_cleanup
+		fi
+	echo -n "."
+	done
+	echo " done."
+fi
+
+# copy io500 configs over to the io500 clients.
+echo -n "copy io500 configs to the io500 clients. "
+for i in `seq 1 $OB_IO500_CLIENTS`
+do
+	OB_EX_IP="${OB_EX_ETC_HOSTS["$OB_IO500_NAME""${OB_ALPHA[i]}"]}"
+	OB_HOST="$OB_IO500_NAME""${OB_ALPHA[i]}"
 	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		sudo gsutil cp "$OB_BUCKET"/config-custom.ini io500 \
+		sudo gsutil cp "$OB_BUCKET"/config-custom.ini \
+		   "$OB_MPI_REPO"/io500 \
 			> /dev/null 2>&1
 	if [ "$?" -gt "0" ]
 	then
@@ -530,7 +598,7 @@ then
 		ob_cleanup
 	fi
 	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		sudo gsutil cp "$OB_BUCKET"/io500.sh io500 \
+		sudo gsutil cp "$OB_BUCKET"/io500.sh "$OB_MPI_REPO"/io500 \
 			> /dev/null 2>&1
 	if [ "$?" -gt "0" ]
 	then
@@ -538,32 +606,47 @@ then
 		ob_cleanup
 	fi
 
-	# delete all the orangefs servers from the hostfile
-	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		sed -i "/${OB_OFS_NAME}/d" hostfile \
-			> /dev/null 2>&1
+	# copy client hostnames in hostfile to io500/hostfile.
+	scp -o "StrictHostKeyChecking no" \
+		hostfile "$OB_EX_IP":"$OB_MPI_REPO"/io500 > /dev/null 2>&1
 	if [ "$?" -gt "0" ]
 	then
-		echo "purge of servers in hostfile on :""$OB_HOST"": failed."
+		echo -e "\nscp client list file to :"$OB_HOST": failed."
 		ob_cleanup
 	fi
+done
+echo " done."
 
-	# copy remaining client hostnames in hostfile to io500/hostfile.
-	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		"sed 's/^.* //g' hostfile > io500/hostfile" \
-			> /dev/null 2>&1
-	if [ "$?" -gt "0" ]
-	then
-		echo "hostfile copy to io500 dir on :""$OB_HOST"": failed."
-		ob_cleanup
-	fi
-
+# run io500 on the "a" io500 client.
+if [ "$OB_IO500_CLIENTS" -gt "0" ]
+then
+        OB_EX_IP="${OB_EX_ETC_HOSTS["$OB_IO500_NAME""a"]}"
+        OB_HOST="$OB_IO500_NAME""a"
 set -x
+
 	# run io500.sh
 	echo "start io500 on :""$OB_HOST"":."
-	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		'(. .bash_profile;cd io500;. io500.sh config-custom.ini)' \
-			> /dev/null 2>&1
+	if [ "$OB_MPI_TYPE" = "intel" ]
+	then
+		ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
+		  '(. /opt/intel/oneapi/setvars.sh; \
+		     cd '"$OB_MPI_REPO"'/io500; \
+			. io500.sh config-custom.ini)' \
+				> /dev/null 2>&1
+	elif [ "$OB_MPI_TYPE" = "openmpi" ]
+	then
+		ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
+		  '(. '"$OB_MPI_REPO"'/setvars_openmpi.sh; \
+		     cd '"$OB_MPI_REPO"'/io500; \
+			. io500.sh config-custom.ini)' \
+				> /dev/null 2>&1
+	else
+		ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
+		  '(. '"$OB_MPI_REPO"'/setvars_vanilla.sh; \
+		     cd '"$OB_MPI_REPO"'/io500; \
+			. io500.sh config-custom.ini)' \
+				> /dev/null 2>&1
+	fi
 	if [ "$?" -gt "0" ]
 	then
 		echo "io500 failed to run on :""$OB_HOST"":."
