Don't add "slots" to hostfile when using Intel MPI
Intel MPI doesn't support specifying the number of slots per host in
the hostfile. So if Intel is being used and a number of slots other
than 0 was specified, print a warning message and instructions on how
to set the number of processes per node. In addition, set IO500 not to
run upon environment creation so as not to run with an incorrect
process mapping.

Signed-off-by: Mike Marshall <hubcap@omnibond.com>

diff --git a/script b/script
--- a/script
+++ b/script
@@ -776,11 +776,26 @@ then
 fi
 if [ "$OB_SLOTS" -gt "0" ]
 then
-	sed -i "s/$/ slots=$OB_SLOTS/" hostfile
-	if [ "$?" -gt "0" ]
+	if [ "$OB_MPI_TYPE" = "intel" ]
 	then
-		echo "adding slots to hostfile failed."
-		ob_cleanup
+		OB_RUN_IO500=0
+		cat <<- SLOTS_MSG
+
+		*********************** WARNING ***********************
+		 Intel MPI does not support "slots" in the hostfile.
+		 Pass the --perhost option to mpirun/mpiexec instead.
+
+		 IO500 will need to be run manually upon completion.
+		*******************************************************
+
+		SLOTS_MSG
+	else
+		sed -i "s/$/ slots=$OB_SLOTS/" hostfile
+		if [ "$?" -gt "0" ]
+		then
+			echo "adding slots to hostfile failed."
+			ob_cleanup
+		fi
 	fi
 fi
 
