Add support for placement groups
Required refactoring the way we create instances and collect IPs

diff --git a/script b/script
--- a/script
+++ b/script
@@ -5,7 +5,7 @@
 # function to call on normal exit and on any failure
 ob_cleanup()
 {
-	echo "remember to clean up test instances"
+	echo "remember to clean up test instances and resource policies"
 	exit
 }
 
@@ -80,6 +80,9 @@ OB_SSD_ARG=" --local-ssd interface=nvme"
 OB_SSD_DEV="/dev/nvme0n"
 OB_MDADM="mdadm --create /dev/md0 --level=0 --raid-devices="
 OB_MOUNT_POINT="/var/lib/orangefs"
+
+# If set, will create all instances inside a compact placement group.
+OB_USE_PLACEMENT_GROUP=1
 
 OB_NET_INT=""
 #OB_NET_INT=" --network-interface=nic-type=GVNIC"
@@ -264,55 +267,136 @@ echo ":""$OB_OFS_CONFIG"":"
 
 eval "$OB_OFS_CONFIG"
 
-# associative array for host names to ip addrs
-declare -A OB_EX_ETC_HOSTS # external addrs
-declare -A OB_IN_ETC_HOSTS # internal addrs
+echo ""
 
-# create the ofs servers and collect their external and internal IP addrs
+# create a compact placement group
+OB_POLICY_CREATE="gcloud compute resource-policies create"
+OB_POLICY_TYPE="group-placement"
+OB_COLLOCATION="COLLOCATED"
+OB_POLICY_PREFIX="pattern1-io500-pg"
+
+if [ "$OB_USE_PLACEMENT_GROUP" -gt "0" ]
+then
+	ts=$(date "+%Y%m%d-%H%M%S")
+	policy_name="${OB_POLICY_PREFIX}-${ts}"
+	vm_count=$(( OB_OFS_SERVERS + OB_IO500_CLIENTS ))
+
+	OB_CMD="$OB_POLICY_CREATE $OB_POLICY_TYPE $policy_name"
+	OB_CMD+=" --collocation=$OB_COLLOCATION"
+	OB_CMD+=" --vm-count=$vm_count"
+	#echo $OB_CMD
+	eval $OB_CMD
+	if [ "$?" -gt "0" ]
+	then
+		echo "creation of "$policy_name" failed."
+		ob_cleanup
+	fi
+
+	OB_POLICY_OPTS=" --resource-policies=$policy_name"
+	OB_POLICY_OPTS+=" --maintenance-policy=TERMINATE"
+	OB_POLICY_OPTS+=" --no-restart-on-failure"
+
+	# TODO: add cleanup message/instructions for policy to ob_cleanup
+else
+	OB_POLICY_OPTS=""
+fi
+
+echo ""
+
+# create the ofs servers
 for i in `seq 1 $OB_OFS_SERVERS`
 do
 	OB_CMD="$OB_CREATE""$OB_OFS_NAME""${OB_ALPHA[i]}"
 	OB_CMD="$OB_CMD""$OB_IMAGE""$OB_OFS_MACHINE""$OB_SCOPE"
 	OB_CMD="$OB_CMD""$OB_NET_INT""$OB_NET_PERF"
+	OB_CMD="$OB_CMD""$OB_POLICY_OPTS"" --async"
+	OB_CMD="$OB_CMD"" --no-user-output-enabled"
 	for j in `seq 1 $OB_SSD_NUM`
 	do
 		OB_CMD="$OB_CMD""$OB_SSD_ARG"
 	done
-#	echo $OB_CMD
-#	exit
+	#echo $OB_CMD
 	eval $OB_CMD
 	if [ "$?" -gt "0" ]
 	then
 		echo "creation of ""$OB_OFS_NAME""${OB_ALPHA[i]}"" failed."
 		ob_cleanup
 	fi
-	OB_EX_ETC_HOSTS["$OB_OFS_NAME""${OB_ALPHA[i]}"]=`gcloud compute instances describe "$OB_OFS_NAME""${OB_ALPHA[i]}" --format='get(networkInterfaces[0].accessConfigs[0].natIP)'`
-	if [ "$?" -gt "0" ]
-	then
-		echo "no external ip for ""$OB_OFS_NAME""${OB_ALPHA[i]}""."
-		ob_cleanup
-	fi
-	OB_IN_ETC_HOSTS["$OB_OFS_NAME""${OB_ALPHA[i]}"]=`gcloud compute instances describe "$OB_OFS_NAME""${OB_ALPHA[i]}" --format='get(networkInterfaces[0].networkIP)'`
-	if [ "$?" -gt "0" ]
-	then
-		echo "no internal ip for ""$OB_OFS_NAME""${OB_ALPHA[i]}""."
-		ob_cleanup
-	fi
 done
 
-echo ""
-
-# create the io500 servers and collect their external and internal IP addrs
+# create the io500 clients
 for i in `seq 1 $OB_IO500_CLIENTS`
 do
 	OB_CMD="$OB_CREATE""$OB_IO500_NAME""${OB_ALPHA[i]}"
 	OB_CMD="$OB_CMD""$OB_IMAGE""$OB_IO500_MACHINE""$OB_SCOPE"
 	OB_CMD="$OB_CMD""$OB_NET_INT""$OB_NET_PERF"
+	OB_CMD="$OB_CMD""$OB_POLICY_OPTS"" --async"
+	OB_CMD="$OB_CMD"" --no-user-output-enabled"
 #	echo $OB_CMD
 	eval $OB_CMD
-	OB_EX_ETC_HOSTS["$OB_IO500_NAME""${OB_ALPHA[i]}"]=`gcloud compute instances describe "$OB_IO500_NAME""${OB_ALPHA[i]}" --format='get(networkInterfaces[0].accessConfigs[0].natIP)'`
-	OB_IN_ETC_HOSTS["$OB_IO500_NAME""${OB_ALPHA[i]}"]=`gcloud compute instances describe "$OB_IO500_NAME""${OB_ALPHA[i]}" --format='get(networkInterfaces[0].networkIP)'`
+	if [ "$?" -gt "0" ]
+	then
+		echo "creation of ""$OB_IO500_NAME""${OB_ALPHA[i]}"" failed."
+		ob_cleanup
+	fi
 done
+
+# function to wait for a launched instance to reach the RUNNING state
+wait_for_instance() {
+	instance_name=$1
+	instance_status=""
+
+	echo -n "Waiting for instance ${instance_name}... "
+	while [ "$instance_status" != "RUNNING" ]
+	do
+		sleep $OB_SLEEP
+		instance_status=`gcloud compute instances describe $instance_name --format='get(status)'`
+	done
+	echo "done."
+}
+
+# associative array for host names to ip addrs
+declare -A OB_EX_ETC_HOSTS # external addrs
+declare -A OB_IN_ETC_HOSTS # internal addrs
+
+# function to collect an instance's external and internal IP addresses
+collect_ips() {
+	instance_name=$1
+
+	OB_EX_ETC_HOSTS[$instance_name]=`gcloud compute instances describe $instance_name --format='get(networkInterfaces[0].accessConfigs[0].natIP)'`
+	if [ "$?" -gt "0" ]
+	then
+		echo "no external ip for ${instance_name}."
+		ob_cleanup
+	fi
+
+	OB_IN_ETC_HOSTS[$instance_name]=`gcloud compute instances describe $instance_name --format='get(networkInterfaces[0].networkIP)'`
+	if [ "$?" -gt "0" ]
+	then
+		echo "no internal ip for ${instance_name}."
+		ob_cleanup
+	fi
+}
+
+# collect the servers' external and internal IP addrs once they lanuch
+for i in `seq 1 $OB_OFS_SERVERS`
+do
+	instance_name="$OB_OFS_NAME""${OB_ALPHA[i]}"
+
+	wait_for_instance $instance_name
+	collect_ips $instance_name
+done
+
+# collect the clients' external and internal IP addrs once they launch
+for i in `seq 1 $OB_IO500_CLIENTS`
+do
+	instance_name="$OB_IO500_NAME""${OB_ALPHA[i]}"
+
+	wait_for_instance $instance_name
+	collect_ips $instance_name
+done
+
+echo ""
 
 # Don't continue if unable to connect to ssh port in the allotted time.
 echo -n "Testing connectivity to port 22 on orangefs servers. "
