script: added ssh-keyscan stanza
Signed-off-by: Mike Marshall <hubcap@omnibond.com>

diff --git a/script b/script
--- a/script
+++ b/script
@@ -406,35 +406,32 @@ echo " done."
 
 # "third party" ssh tools such as mpirun need to be usable
 # on the clients without interaction from a human... set up
-# passwordless ssh access between them.
+# passwordless ssh access between the client instances:
+#  + generate a keypair for each client
+#  + collect all the public keys
+#  + fixup authorized_keys and known_hosts on each client
+#
 echo -n "create ssh key pairs for the clients"
 for i in `seq 1 $OB_IO500_CLIENTS`
 do
 	OB_EX_IP="${OB_EX_ETC_HOSTS["$OB_IO500_NAME""${OB_ALPHA[i]}"]}"
 	OB_HOST="$OB_IO500_NAME""${OB_ALPHA[i]}"
 	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		ssh-keygen -b 2048 -t rsa -f /tmp/id_rsa -q -N \"\" \
+		ssh-keygen -b 2048 -t rsa -f .ssh/id_rsa -q -N \"\" \
 			> /dev/null 2>&1
 	if [ "$?" -gt "0" ]
 	then
 		echo -e "\nssh-keygen on :"$OB_HOST": failed."
 		ob_cleanup
 	fi
+
 	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		cp /tmp/{id_rsa,id_rsa.pub} .ssh > /dev/null 2>&1
-	if [ "$?" -gt "0" ]
-	then
-		echo -e "\ncopy ssh keys on :"$OB_HOST": failed."
-		ob_cleanup
-	fi
-	ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
-		cat /tmp/id_rsa.pub >> pub.keys 2> /dev/null
+		cat .ssh/id_rsa.pub >> pub.keys 2> /dev/null
 	if [ "$?" -gt "0" ]
 	then
 		echo -e "\nretrieve pub key from :"$OB_HOST": failed."
 		ob_cleanup
 	fi
-	echo -n "."
 done
 for i in `seq 1 $OB_IO500_CLIENTS`
 do
@@ -448,6 +445,20 @@ do
 		echo -e "\n copy public keys to :"$OB_HOST": failed."
 		ob_cleanup
 	fi
+
+	for j in `seq 1 $OB_IO500_CLIENTS`
+	do
+		jth_host="$OB_IO500_NAME""${OB_ALPHA[j]}"
+		ssh -o "StrictHostKeyChecking no" "$OB_EX_IP" \
+			'ssh-keyscan -H '"$jth_host"' >> .ssh/known_hosts' \
+				2> /dev/null
+		if [ "$?" -gt "0" ]
+		then
+			echo -e "\n ssh-keyscan on :"$jth_host": failed."
+			ob_cleanup
+		fi
+	done
+	echo -n "."
 done
 echo " done."
 
